Kitware/trame

examples/VTK/Applications/VTPViewer/app.py
trame/__init__.py
trame/state/__init__.py
trame/state/core.py

This allows for state access like this:
```python
from trame import state
state.field = value
result = state.field
```
As opposed to:
```python
from trame import get_state, update_state
update_state("field", value)
result, = get_state("field")
```
However, `update_state()` should still be used when extra arguments are needed (e.g., `force=True`), and `get_state()` can still be used for passing in multiple names.
The VTPViewer was modified to demonstrate this change.

feat(state): add class for pythonic state access

---

trame/__init__.py
trame/state/core.py
trame/trigger/__init__.py
trame/trigger/controller.py
trame/utils/__init__.py
trame/utils/string.py

This class allows function proxies to be used for callbacks, where the underlying function may be
temporarily undefined or the definition may change in the future. An object of the Controller
class may be imported via `from trame import controller as ctrl`.

feat(Controller): add Controller class for function proxies

---

trame/__init__.py
trame/state/core.py

feat(State): add `__setitem__` and `__getitem__`
This allows state attributes to be accessed with brackets, such as `field = state["field"]`, or
`state["field"] = field`.
feat(State): add update() method
This method functions similar to the update() method of dictionaries, in that it is passed a
dictionary, and each key is assigned to it's corresponding value in the state.

Add State __setitem__, __getitem__, and update()

---

trame/__init__.py
trame/internal/__init__.py
trame/internal/app/app.py
trame/internal/dev/__init__.py
trame/internal/dev/dev.py
trame/internal/triggers/core.py
trame/layouts/core.py

This function takes modules to reload when the reload button is pressed, which is visible if the 
`--dev` argument is passed. This appears to be working both for running
`trame --dev <single_file>`, and by calling the `setup_dev()` function in a custom trame
application, along with passing the `--dev` flag to the python command. The function will
additionally call an `on_reload` function in any module it finds, and pass it another function that
can be used to reload more modules.

feat(setup_dev): add setup_dev() function for reloading trame applications

---

.github/workflows/docker.yml
docker/Dockerfile.common
docker/Dockerfile.conda
docker/Dockerfile.pip
docker/scripts/conda/activate_venv.sh
docker/scripts/conda/create_venv.sh
docker/scripts/conda/install_requirements.sh
docker/scripts/entrypoint.sh
docker/scripts/fix_uid_gid.sh
docker/scripts/pip/activate_venv.sh
docker/scripts/pip/create_venv.sh
docker/scripts/pip/install_requirements.sh
docker/scripts/server.sh

This places common Dockerfile code in `Dockerfile.common`, and adds a `Dockerfile.pip` and
`Dockerfile.conda` which are based off of it. It also adds scripts unique to conda and pip in
`conda` and `pip` subdirectories, which get copied via their respective Dockerfiles.
This also adds conda and glvnd builds to CI.

Add conda docker image

---

.github/workflows/docker.yml

Apparently, glvnd devel is required to run ParaView, since it includes libOpenGL, but the runtime
does not.

chore(docker): use glvnd devel instead of runtime

---

trame/layouts/core.py

These kwargs get forwarded to `App.run_server()`. An example of `exec_mode` is provided in the documentation.

feat(layout): add kwargs to AbstractLayout.start()

---

trame/internal/utils/logging.py
trame/jupyter/__init__.py
trame/jupyter/display.py
trame/jupyter/proxy.py
trame/layouts/core.py

The utility functions can be helpful both for running trame in the jupyter event loop and for running trame as a separate jupyter server proxy process. Cookie cutter examples are soon to follow.

feat(jupyter): add utility functions for running in jupyter

---

examples/VTK/SimpleCone/RemoteRendering.py
trame/internal/utils/desktop.py

fix(pywebview): support newer versions and windows
Newer versions of pywebvue set the closing events on `window.events.closing` instead of on
`window.closing`. And Windows appears to freeze up if we call `window.destroy()`. In my testing,
it appears that both Windows and Linux close cleanly without `window.destroy()`, so it was removed.
fix(RemoteRendering.py): hide render window and support multiprocessing on Windows
This hides the extra render window that appears, and adds support for multiprocessing on Windows,
where `freeze_support()` is required to prevent infinite recursion when starting the program in
other processes. This also shows that `layout.start_desktop_window()` may be used instead.

Pywebview fixes

---

examples/PlainPython/Menu/README.md
examples/PlainPython/Menu/app.py
trame/html/__init__.py

v-on and v-bind were not mapped from python keys to vue keys, which made it not possible to implement and example like this:
```python
with vuetify.VMenu():
with vuetify.Template(v_slot_activator="{ on, attrs }"):
with vuetify.VBtn(icon=True, v_bind="attrs", v_on="on", v_on_click="test"):
vuetify.VIcon("mdi-dots-vertical")
with vuetify.VList(), vuetify.VListItem(
v_for="(item, i) in menu_items",
key="i",
value=["item"],
):
vuetify.VBtn(
"{{ item }}",
click=(print_item, "[item]"),
)
```
Note: The list of `v_on_names` does not cover all possibilities yet. Since you can chain most of the keywords in different ways, we should probably build the list programmatically. (e.g. `v-on:click.self.stop.prevent` etc.)

Implement v-on and v-bind

---

trame/app/__init__.py
trame/app/mimetypes.py
trame/assets/local.py

On Windows, the mimetypes are obtained from the registry. However,
the mimetype for javascript files is broken. Add some code to ensure
that javascript files are identified correctly.
This also adds some infrastructure for adding extra mimetypes that
persist even if `mimetypes.init()` is called.
This fixes the issue that I was encountering on Windows.

Ensure javascript files get the correct mimetype

---

docker/scripts/build.sh
docker/scripts/server.sh
docker/scripts/start.sh

The commit messages are pasted below:
This allows the user to separate out building the venv, launcher, and www.
The default behavior is that all will build if they do not exist. If they do exist,
then they will not be built.
However, the user can now select some options via a `TRAME_BUILD` environment variable.
If this string contains (single or any combination of) "venv", "launcher", or "www",
then those respective parts will be re-built, even if they already exist.
Additionally, a "no_www" can be specified in the `TRAME_BUILD` environment variable,
which indicates to skip the `www` generation, even if it does not exist.
If a `TRAME_USE_HOST` environment variable is defined, then this will replace
`USE_HOST` in the final copy of the launcher json file.
If `TRAME_USE_HOST` contains …

Additional docker options

---

docs/content/index.pug

This commit fixes a regression introduced in 5f55d6a57 (docs(website): update content to match new api) updating the text describing the license to mention "Apache License Version 2.0" instead of "BSD-3".
The text now described the license effectively associated with the trame v2 project originally introduced in 0e44015c8 (trame a framework to write ubiquitous applications in Python).
For reference, trame v1 license  (originally introduced in e8fe5944b (chore: Getting started)) was BSD-3.

doc(website): Fix license reference

---

setup.cfg
trame/app/__init__.py

BREAKING CHANGE: In December 2023, the default client type will be vue3
A clear and concise description of what the problem was and how this pull request solves it.
fix #ISSUE_NUMBER

feat(v3): Streamline trame for vue3 support

---

examples/05_charts/Matplotlib/00_matplotlib-charts.py

Two small fixes to the matplotlib example.
The matplotlib example 05_charts/Matplotlib/00_matplotlib-charts.py will replot the figure when you resize the window. When you resize it for a couple of seconds, you will get the message:
~/trame/examples/05_charts/Matplotlib/00_matplotlib-charts.py:45: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (matplotlib.pyplot.figure) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam figure.max_open_warning). Consider using matplotlib.pyplot.close(). fig, ax = plt.subplots(**figure_size())
I just placed a
plt.close('all')
before the fig,ax=plt.subplots() line and I did not get this message anymore.
00_matplotlib-charts.py:118: UserWarning: …

docs(matplotlib): update examples to close the plots

---

examples/07_paraview/Docker/Dockerfile
examples/07_paraview/Docker/SimpleCone.py
examples/07_paraview/Docker/setup/apps.yml
examples/07_paraview/Docker/setup/requirements.txt

New example allowing to run 07_paraview/SimpleCone from a headless docker container using X11 virtual frame buffer with Paraview 5.12.0-RC1 and Python 3.10
To run the example:
```
docker build -t paraview-trame .
docker run -ti -p 1234:8080 paraview-trame
```
SimpleCone should be accessible at localhost:1234

Add Paraview Docker example

---

docs/vitepress/examples/apps/community.md

Images for MRI Viewer do not show up on [the website](https://kitware.github.io/trame/examples/apps/community.html).
This is the fix for it.

docs(community): fix image urls

---

trame/app/__init__.py

This PR adds type hints to the `trame/app/__init__.py` file so that `get_client` and `get_server` have type hints.

Add type hints in trame/app/__init__.py

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Trame Guru](https://gurubase.io/g/trame) to Gurubase. Trame Guru uses the data from this repo and data from the [docs](https://kitware.github.io/trame/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Trame Guru", which highlights that Trame now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …

Introducing Trame Guru on Gurubase.io

---

tests/test_decorators.py
trame/decorators/klass.py

Support class inheritance for decorated classes.

feat(TrameApp): Support decorated class inheritance

---

.github/workflows/docker.yml

Could the Trame image be built against Python 3.11 as well as 3.9 and 3.10?
My two main points are:
- Trame and vtk already support Python 3.11 (I was running 3.11 before I dockerised my application)
- It would allow users to benefit from [the performance boost of 3.11](https://docs.python.org/3/whatsnew/3.11.html#faster-cpython)
- specifically `Interpreter startup is now 10-15% faster in Python 3.11.`, which would reduce the delay in spinning up the new Python process when a new `wslink` session is created

Build Python 3.11 image

---

docker/Dockerfile.common

When installing `gosu` using `apt`, [the latest available version is 1.14.1](https://packages.ubuntu.com/jammy/gosu).
When pointing Docker Scout at the image, it identifies this as bringing very many `critical` and `high` related vulnerabilities, related to the fact that it bundles golang 1.18.2.
This PR should address this by installing the latest `gosu` every time instead.

Install `gosu` from `tianon/gosu` image instead of apt

---

.github/workflows/docker.yml

Reverts Kitware/trame#712
Some more changes needs to be made to support Ubuntu 24.04

Revert "Build Docker container for Python 3.12, on top of Ubuntu 24.04"

---

docs/vitepress/guide/tutorial/html.md

Improve documentation regarding the difference between strings and expressions.

doc(html): precise the usage of parentheses for expressions
